name: "aksh rocketmq"
"on": workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: apache/rocketmq
          path: rocketmq
          fetch-depth: 1
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
      - name: Build
        working-directory: rocketmq
        run: mvn -B compile -DskipTests 2>&1 || true
